// Command agentdenygen renders internal/agentdeny.GatedCommands into
// docs/agent-deny-rules.md. It is the single converter behind `make generate` for this
// document; edit internal/agentdeny/rules.go (the canonical list) or this file's static
// prose sections, never docs/agent-deny-rules.md directly — `make check-generate` fails
// if the rendered doc has drifted from either source.
//
// This is TASK-286's binding for completion criterion 1 ("a new gated command cannot
// ship without a rule"): adding an entry to GatedCommands and forgetting to regenerate
// this doc fails CI. It is not yet a binding against the live cobra command tree —
// TASK-282 has not landed 'config env seal'/'config env show' in this checkout as of
// this card, so there is no command tree to check against. See this doc's own "Binding
// this list to the CLI" section for the follow-up this leaves recorded.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ScriptonBasestar/dva/internal/agentdeny"
)

func main() {
	root := flag.String("root", ".", "repo root")
	flag.Parse()

	out := filepath.Join(*root, "docs", "agent-deny-rules.md")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "agentdenygen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(out, []byte(render()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "agentdenygen:", err)
		os.Exit(1)
	}
	fmt.Println("Generated:", out)
}

func render() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n## Gated commands\n\n")
	b.WriteString("| ID | Command | Deny patterns | Reason | Source |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, command := range agentdeny.GatedCommands {
		patterns := make([]string, len(command.Patterns()))
		for i, p := range command.Patterns() {
			patterns[i] = "`" + p + "`"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s |\n",
			command.ID, command.Argv, strings.Join(patterns, "<br>"), command.Reason, command.Source)
	}
	b.WriteString(coverageTable)
	b.WriteString(destructiveInteractions)
	b.WriteString(honestLimits)
	b.WriteString(binding)
	return b.String()
}

const header = `# DO NOT EDIT — generated by 'make generate' from internal/agentdeny/rules.go and tools/agentdenygen/main.go

# Agent-runtime deny rules

DVA cannot reliably learn that its own caller is an AI agent (TASK-281 §3-6): every
signal at the CLI layer is advisory and caller-supplied, never a security boundary. The
one layer that does know its caller's nature is the agent runtime itself: most already
refuse a tool call before it reaches human approval when a settings file says to. This
package (` + "`internal/agentdeny`" + `) is the canonical source of the deny-pattern list DVA
deploys into that layer, via ` + "`dva agent-deny install|status|uninstall`" + `.
`

const coverageTable = `
## Runtime coverage

Every runtime is listed explicitly — including the ones this card does not implement a
projection for — because a runtime silently missing from this table is worse than one
marked unsupported: a reader would otherwise have no way to tell "not covered" from
"forgotten."

| Runtime | Deny mechanism | Status |
|---|---|---|
| Claude Code | ` + "`.claude/settings.json`" + `, ` + "`permissions.deny`" + ` array of ` + "`Bash(<prefix> *)`" + ` patterns — ` + "`Bash(...)`" + ` is required (a bare string names a tool, not a command) and the space before ` + "`*`" + ` matters (matches the prefix and trailing args, not a neighbor prefix) | **Implemented.** ` + "`dva agent-deny install/status/uninstall --scope user\\|project`" + ` targets this. |
| OpenCode | Project/user ` + "`opencode.json`" + `, permission-style deny rules | Researched, not implemented. Deny-array key and glob semantics were not independently verified against a live install. Recorded as follow-up. |
| Antigravity | Same family as Claude Code/OpenCode per ` + "`skills/_targets.yaml`" + ` | Researched, not implemented. No independently verified settings-file/permission-key documentation found. |
| Cursor (CLI/editor) | Documented prefix/glob command allow-deny lists in some Cursor releases | Researched, not implemented. MDC rules are context injection, not permission enforcement; no verified deny-rule format confirmed. |
| Codex CLI | An experimental execpolicy mechanism | Researched, not implemented. Unverified against a shipped, stable format. |
| Grok CLI (xAI) | Unverified | **Unsupported.** No independently verifiable deny/permission mechanism found. |
| agent-mesh (` + "`am`" + `) | N/A | **Not applicable.** DVA's own workflow tooling, not a third-party agent runtime. |

Only Claude Code has an implemented, tested projection as of TASK-286. Every other
runtime above is either explicitly unsupported or recorded as researched-but-unimplemented.
`

const destructiveInteractions = `
## Destructive interactions (Project scope)

In addition to the global secret commands, ` + "`dva agent-deny install --scope project`" + `
dynamically inspects ` + "`dva.yml`" + ` and projects deny patterns for commands marked ` + "`destructive: true`" + `
(TASK-321). For each destructive interaction (e.g. ` + "`db reset`" + `), two patterns are projected:
- ` + "`Bash(dva <name> *)`" + `
- ` + "`Bash(dva run <name> *)`" + `

Interactive CLI invocations prompt for confirmation (` + "`[y/N]`" + `) unless ` + "`--yes`" + ` (` + "`-y`" + `) is passed.
`

const honestLimits = `
## Honest limits

This is a **policy control the runtime enforces on trust**, not a boundary DVA itself
enforces. The deny-rule file is an ordinary file both a human and an agent can edit —
nothing here stops an agent from editing it before invoking a gated command, the same way
nothing stops a person from doing so.

The threat model this defends is a **compliant agent that was never told not to do
something** — not an adversarial one. Within that model it is highly effective: a
compliant agent checks its own runtime's deny rules before ever emitting the tool call.
Outside that model — an agent deliberately working around its own guardrails — this layer
does not hold, and does not claim to:

- **Shell obfuscation, wrapper scripts, base64/eval tricks, and a project's own
  ` + "`dva run`" + ` interaction that internally shells out to a gated command under a different
  name** are not covered by a literal argv-prefix pattern. See
  ` + "`internal/agentdeny/rules.go`" + `'s ` + "`Patterns`" + ` doc and ` + "`match_test.go`" + `'s
  ` + "`TestKnownUncoveredInvocations`" + ` for what is and is not matched.
- **Path-qualified invocation** — e.g. ` + "`./bin/dva config env show`" + ` (` + "`make build`" + `
  produces ` + "`bin/dva`" + `) — is not covered; the pattern is anchored on literal argv
  ` + "`dva ...`" + `, and a path prefix is a different literal string.
- **Environment-runner wrappers** — ` + "`mise exec --`" + `, ` + "`devbox run`" + `, ` + "`direnv exec`" + `,
  ` + "`docker exec`" + ` — are not covered. Claude Code strips a leading env assignment and
  ` + "`timeout`" + `/` + "`nice`" + `/` + "`command`" + `/` + "`xargs`" + ` wrappers before matching, but its stripped-wrapper
  list excludes these, so a gated command run through one bypasses the pattern.
- **pty hijacking** (TASK-281 §3-6's residual gap: an agent allocating a pty via e.g.
  ` + "`script -q /dev/null`" + ` to capture ` + "`/dev/tty`" + `-only output) is out of scope for a
  text-pattern deny rule — it is already an act of bypass intent. TASK-281 §3-6's layered
  strength ordering: DVA's advisory detection < ` + "`/dev/tty`" + `-only output < a runtime deny
  rule (this package) < ` + "`allow_show: false`" + `. The last is strongest, and it is the
  default.

None of this is a defect in the implementation; it is the honest scope of what a
runtime-trusted deny pattern can do, stated so a reader does not mistake "very effective
against a compliant agent" for "a DVA-enforced security boundary."
`

const binding = `
## Binding this list to the CLI

` + "`make check-generate`" + ` fails if this document has drifted from
` + "`internal/agentdeny.GatedCommands`" + ` — the source list above — so a change to that list
that is not accompanied by regenerating this doc is caught in CI.

That only proves the doc agrees with the list it came from. The binding to the *live*
command tree is ` + "`internal/cli.TestGatedCommandsCoverEveryGatedSurface`" + ` (TASK-337),
run by ` + "`make test`" + ` in CI. It derives the gated surface from ` + "`internal/cli`" + `'s own
source rather than a second declared list — a gated command refuses with a
` + "`*_not_enabled`" + ` code, and that refusal is the gate — then rebuilds each argv from the
` + "`AddCommand`" + ` calls that build the real tree. It fails both ways: a gated command with
no entry here, and an entry whose argv no gated command produces.

## What "never clobbers" means here

Installing merges the desired deny patterns into the target file's
` + "`permissions.deny`" + ` array by parsing it, adding only the entries that are missing, and
re-serializing. Every other key's *value* — including sibling ` + "`permissions.allow`" + `/
` + "`permissions.ask`" + ` arrays, any pre-existing user-added deny entries, and every unrelated
top-level key — survives byte-for-byte in content, proven by
` + "`internal/agentdeny/deploy_test.go`" + `'s ` + "`TestInstallDoesNotClobberSiblingContent`" + `. What
is not preserved is the file's exact formatting (indentation, key order) of the
containers this package touches — re-serializing a Go map does not reproduce arbitrary
source whitespace or key ordering. This is a deliberate, recorded trade-off: byte-level
source-position surgery was judged disproportionate to the risk it would close, given
that no *content* is ever lost or reinterpreted.

## Ownership model

` + "`dva agent-deny install/status/uninstall`" + ` reuses ` + "`internal/skillinstall.Scope`" + `
directly (` + "`--scope user or project`" + `) and a skillinstall-style receipt
(` + "`internal/agentdeny/receipt.go`" + `, same atomic temp-file+fsync+rename write discipline
as ` + "`internal/skillinstall`" + `'s own receipts) to track exactly which pattern strings DVA
added at a destination, so status can detect a locally removed/edited DVA-owned pattern
and uninstall can remove only entries that are still present verbatim — refusing the
whole operation on any drift rather than guessing which are still safe to remove.

This package does **not** reuse skillinstall's takeover/backup machinery: that solves a
different problem (a skill install owns a whole destination directory and can collide
with a foreign, non-DVA-created one of the same name). A deny-rule install only ever
merges known strings into one JSON array in a file the user may already own — it never
replaces or deletes content it doesn't recognize, so there is no foreign collision for a
takeover to resolve.

## init integration boundary

` + "`dva init`" + ` does not write this or any other agent settings file as part of this card.
` + "`internal/cli/init.go`" + `, ` + "`internal/cli/init_scaffold.go`" + `, and their tests have zero
references to ` + "`skillinstall`" + ` or a settings file (confirmed by grep) — deploying deny
rules stays an explicit, separate ` + "`dva agent-deny install`" + ` invocation. Whether/how
` + "`init`" + ` should *recommend* running it is TASK-249's boundary, not this card's.
`
