package skillinstall

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/ScriptonBasestar/dva/internal/skillclaim"
	bundled "github.com/ScriptonBasestar/dva/skills"
)

func TestRuntimePaths(t *testing.T) {
	t.Parallel()
	home := t.TempDir()
	project := t.TempDir()
	tests := []struct {
		scope   Scope
		runtime Runtime
		want    string
	}{
		{ScopeUser, RuntimeClaudeCode, ".claude/skills"},
		{ScopeUser, RuntimeCodex, ".agents/skills"},
		{ScopeUser, RuntimeOpenCode, ".config/opencode/skills"},
		{ScopeUser, RuntimeAgentMesh, ".config/agent-mesh/skills/dva"},
		{ScopeUser, RuntimeGrok, ".grok/skills"},
		{ScopeUser, RuntimeAntigravity, ".gemini/config/skills"},
		{ScopeProject, RuntimeClaudeCode, ".claude/skills"},
		{ScopeProject, RuntimeCodex, ".agents/skills"},
		{ScopeProject, RuntimeOpenCode, ".opencode/skills"},
		{ScopeProject, RuntimeAgentMesh, ".agent-mesh/skills/dva"},
		{ScopeProject, RuntimeGrok, ".grok/skills"},
		{ScopeProject, RuntimeAntigravity, ".agents/skills"},
	}
	for _, test := range tests {
		t.Run(string(test.scope)+"/"+string(test.runtime), func(t *testing.T) {
			got, err := runtimePath(test.runtime, test.scope, home, project)
			if err != nil {
				t.Fatal(err)
			}
			base := home
			if test.scope == ScopeProject {
				base = project
			}
			if want := filepath.Join(base, test.want); got != want {
				t.Fatalf("path = %q, want %q", got, want)
			}
		})
	}
}

func TestAgentMeshInstallsFlatRenderedSkills(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeAgentMesh)
	result, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := result.Destinations[0].Destination, filepath.Join(options.ProjectRoot, ".agent-mesh", "skills", "dva"); got != want {
		t.Fatalf("destination = %q, want %q", got, want)
	}
	dva, err := os.ReadFile(filepath.Join(result.Destinations[0].Destination, "dva.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"# DVA (Dev Virtual Auto) CLI", "Generated by `dva skill install --runtime agent-mesh`",
		"## Reference: references/commands.md", "## Asset: assets/templates/root-devbox-plan.yml",
		"### DVA Command Reference", "#dva-dva-assets-templates-root-devbox-plan-yml",
	} {
		if !strings.Contains(string(dva), want) {
			t.Errorf("rendered Agent Mesh skill omits %q", want)
		}
	}
	if strings.HasPrefix(string(dva), "---\n") {
		t.Fatal("rendered Agent Mesh skill retained YAML frontmatter")
	}
	if _, err := os.Stat(filepath.Join(result.Destinations[0].Destination, "dva-ci.md")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(result.Destinations[0].Destination, "dva", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Agent Mesh install created native skill directory: %v", err)
	}
	for _, name := range bundled.Names {
		claim, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), filepath.Join(result.Destinations[0].Destination, name+".md"))
		if err != nil || !found {
			t.Fatalf("Agent Mesh claim %s = (%#v, %t, %v)", name, claim, found, err)
		}
		if claim.Name != name || claim.Kind != skillclaim.KindFile || len(claim.Files) != 1 || claim.Files[0].Path != "." {
			t.Fatalf("Agent Mesh claim %s has native semantics: %#v", name, claim)
		}
	}

	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "installed" {
		t.Fatalf("status = %s", status.Destinations[0].Status)
	}
	if _, err := Uninstall(options); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(result.Destinations[0].Destination); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Agent Mesh DVA namespace remains after uninstall: %v", err)
	}
}

func TestAgentMeshRendererInlinesAssetsAndDemotesReferenceHeadings(t *testing.T) {
	t.Parallel()
	contents, err := renderAgentMeshSkill("dva")
	if err != nil {
		t.Fatal(err)
	}
	rendered := string(contents)
	for _, path := range []string{
		"assets/templates/migrate-modes-to-plans.yml", "assets/templates/root-devbox-plan.yml", "assets/templates/subproject-local.yml",
		"references/advanced.md", "references/commands.md", "references/operation-safety.md", "references/patterns.md",
	} {
		if !strings.Contains(rendered, "## "+map[bool]string{true: "Asset", false: "Reference"}[strings.HasPrefix(path, "assets/")]+": "+path) {
			t.Errorf("rendered skill omits inlined %s", path)
		}
	}
	if strings.Contains(rendered, "\n# DVA Command Reference\n") {
		t.Fatal("inlined reference retained an H1 above its Reference parent")
	}
	if !strings.Contains(rendered, "[assets/templates/root-devbox-plan.yml](#dva-dva-assets-templates-root-devbox-plan-yml)") {
		t.Fatal("local resource index did not expose the inlined asset anchor")
	}
	if strings.Contains(rendered, "`[inline ") {
		t.Fatal("renderer produced an inert Markdown link inside inline code")
	}
	if !strings.Contains(rendered, "```yaml\n# dva.yml") {
		t.Fatal("renderer changed a fenced YAML comment")
	}
}

func TestClaimedBundleUpgradeAddsNewSkill(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)

	result, err := Install(options)
	if err != nil {
		t.Fatalf("expand claimed bundle: %v", err)
	}
	if result.Destinations[0].Status != "installed" {
		t.Fatalf("expanded bundle status = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(filepath.Join(target.path, "dva-ci", "SKILL.md")); err != nil {
		t.Fatalf("expanded bundle did not install dva-ci: %v", err)
	}
	updated, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read expanded receipt = (%#v, %t, %v)", updated, found, err)
	}
	if len(updated.Files) <= len(oldReceipt.Files) || !containsSkillFiles(updated.Files, "dva-ci") {
		t.Fatalf("expanded receipt files do not include dva-ci: %v", updated.Files)
	}
	assertClaimConsumers(t, options, target.path, []string{"grok"})
}

func TestClaimedFlatBundleUpgradeAddsNewSkill(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeAgentMesh)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)

	if _, err := Install(options); err != nil {
		t.Fatalf("expand claimed flat bundle: %v", err)
	}
	if _, err := os.Stat(claimDestination(target, "dva-ci")); err != nil {
		t.Fatalf("expanded flat bundle did not install dva-ci: %v", err)
	}
	updated, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read expanded flat receipt = (%#v, %t, %v)", updated, found, err)
	}
	if len(updated.Files) <= len(oldReceipt.Files) || !containsSkillFiles(updated.Files, "dva-ci") {
		t.Fatalf("expanded flat receipt files do not include dva-ci: %v", updated.Files)
	}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	claims, err := projectedClaims(target, options.Scope, options.Runtimes, bundle, skillclaim.StateActive, "flat-upgrade-check")
	if err != nil {
		t.Fatal(err)
	}
	if err := verifyClaimsUnlocked(filepath.Dir(options.StateRoot), claims); err != nil {
		t.Fatalf("expanded flat bundle claims: %v", err)
	}
}

func TestClaimedBundleUpgradeRefusesForeignNewSkillCollision(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)
	foreign := filepath.Join(target.path, "dva-ci", "foreign-marker")
	if err := os.MkdirAll(filepath.Dir(foreign), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(foreign, []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := Install(options); err == nil || !strings.Contains(err.Error(), "newly bundled DVA skill") {
		t.Fatalf("claimed expansion accepted foreign dva-ci collision: %v", err)
	}
	contents, err := os.ReadFile(foreign)
	if err != nil || string(contents) != "foreign" {
		t.Fatalf("foreign collision changed = %q, %v", contents, err)
	}
	assertClaimedBundleState(t, options, target, oldReceipt)
}

func TestClaimedBundleUpgradeRollsBackAfterReceiptFailure(t *testing.T) {
	t.Parallel()
	if runtime.GOOS == "windows" {
		t.Skip("directory permission failure injection is not portable to Windows")
	}
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)
	receiptDir := filepath.Dir(receiptPath(options.StateRoot, target.path))
	if err := os.Chmod(receiptDir, 0o500); err != nil {
		t.Skipf("cannot make receipt directory read-only: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(receiptDir, 0o755) })
	probe, probeErr := os.CreateTemp(receiptDir, ".permission-probe-")
	if probeErr == nil {
		_ = probe.Close()
		_ = os.Remove(probe.Name())
		_ = os.Chmod(receiptDir, 0o755)
		t.Skip("cannot enforce receipt directory write failure in this environment")
	}
	_, err := Install(options)
	if restoreErr := os.Chmod(receiptDir, 0o755); restoreErr != nil {
		t.Fatal(restoreErr)
	}
	if err == nil || !strings.Contains(err.Error(), "update receipt") {
		t.Fatalf("claimed expansion succeeded despite receipt failure: %v", err)
	}
	assertClaimedBundleState(t, options, target, oldReceipt)
	if _, err := os.Stat(filepath.Join(target.path, "dva-ci")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("rollback left new skill behind: %v", err)
	}
}

func TestReplaceSkillDirectoriesRollsBackEarlierMove(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	for _, name := range bundled.Names {
		root := filepath.Join(destination, name)
		if err := os.MkdirAll(root, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "old-marker"), []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	renameCalls := 0
	failingRename := func(oldPath, newPath string) error {
		renameCalls++
		if renameCalls == 3 {
			return errors.New("injected second-skill backup failure")
		}
		return os.Rename(oldPath, newPath)
	}
	if _, _, err := replaceSkillDirectoriesWithRename(destination, files, true, ownedSkillNames(files), failingRename); err == nil {
		t.Fatal("replacement succeeded despite injected failure")
	}
	for _, name := range bundled.Names {
		contents, err := os.ReadFile(filepath.Join(destination, name, "old-marker"))
		if err != nil {
			t.Fatalf("%s old directory was not restored: %v", name, err)
		}
		if string(contents) != name {
			t.Fatalf("%s marker = %q", name, contents)
		}
	}
	stages, err := filepath.Glob(filepath.Join(destination, ".dva-skill-stage-*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(stages) != 0 {
		t.Fatalf("staging directories remain: %v", stages)
	}
}

func TestClaimedReplacementRefusesLateAddedSkillCollision(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	for _, name := range []string{"dva", "dva-config"} {
		root := filepath.Join(destination, name)
		if err := os.MkdirAll(root, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "old-marker"), []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	oldFiles := withoutCISkill(files)
	foreign := filepath.Join(destination, "dva-ci", "foreign-marker")
	injected := false
	rename := func(oldPath, newPath string) error {
		if !injected && oldPath == filepath.Join(destination, "dva") {
			injected = true
			if err := os.MkdirAll(filepath.Dir(foreign), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(foreign, []byte("foreign"), 0o644); err != nil {
				return err
			}
		}
		return os.Rename(oldPath, newPath)
	}
	if _, _, err := replaceSkillDirectoriesWithRename(destination, files, true, ownedSkillNames(oldFiles), rename); err == nil || !strings.Contains(err.Error(), "refusing collision") {
		t.Fatalf("replacement accepted late foreign added-skill collision: %v", err)
	}
	contents, err := os.ReadFile(foreign)
	if err != nil || string(contents) != "foreign" {
		t.Fatalf("late foreign collision changed = %q, %v", contents, err)
	}
	for _, name := range []string{"dva", "dva-config"} {
		contents, err := os.ReadFile(filepath.Join(destination, name, "old-marker"))
		if err != nil || string(contents) != name {
			t.Fatalf("%s old directory was not restored = %q, %v", name, contents, err)
		}
	}
}

func TestNewInstallReplacementRefusesLateCollision(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	collision := filepath.Join(destination, "dva")
	if err := os.MkdirAll(collision, 0o755); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(collision, "foreign-marker")
	if err := os.WriteFile(marker, []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	if _, _, err := replaceSkillDirectories(destination, files, false); err == nil {
		t.Fatal("new install replaced a collision created after preflight")
	}
	contents, err := os.ReadFile(marker)
	if err != nil {
		t.Fatalf("foreign collision was removed: %v", err)
	}
	if string(contents) != "foreign" {
		t.Fatalf("foreign marker changed: %q", contents)
	}
}

func testOptions(t *testing.T, scope Scope, runtimes ...Runtime) Options {
	t.Helper()
	root := t.TempDir()
	return Options{
		Scope:       scope,
		Runtimes:    runtimes,
		HomeDir:     filepath.Join(root, "home"),
		ProjectRoot: filepath.Join(root, "project"),
		StateRoot:   filepath.Join(root, "state"),
	}
}

func withoutCISkill(files []fileHash) []fileHash {
	result := make([]fileHash, 0, len(files))
	for _, file := range files {
		if !strings.HasPrefix(file.Path, "dva-ci/") && file.Path != "dva-ci.md" {
			result = append(result, file)
		}
	}
	return result
}

func containsSkillFiles(files []fileHash, skill string) bool {
	for _, file := range files {
		if strings.HasPrefix(file.Path, skill+"/") || file.Path == skill+".md" {
			return true
		}
	}
	return false
}

// reduceClaimedBundleToTwoSkills models a pre-dva-ci current-schema install:
// it retains the two active DVA claims, receipt, and installed directories.
func reduceClaimedBundleToTwoSkills(t *testing.T, options Options) (destination, receipt) {
	t.Helper()
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: options.Runtimes}
	return target, reduceClaimedBundleAtTarget(t, options, target)
}

func reduceClaimedBundleAtTarget(t *testing.T, options Options, target destination) receipt {
	t.Helper()
	receiptFile := receiptPath(options.StateRoot, target.path)
	record, found, err := readReceipt(receiptFile)
	if err != nil || !found {
		t.Fatalf("read claimed receipt = (%#v, %t, %v)", record, found, err)
	}
	record.Files = withoutCISkill(record.Files)
	record.BundleSHA = sourceBundleSHA(record.Files)
	ciPath := claimDestination(target, "dva-ci")
	if err := os.RemoveAll(ciPath); err != nil {
		t.Fatal(err)
	}
	ciClaimDestination, err := skillclaim.CanonicalDestination(ciPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), ciClaimDestination)); err != nil {
		t.Fatal(err)
	}
	if err := writeReceipt(receiptFile, record); err != nil {
		t.Fatal(err)
	}
	return record
}

func assertClaimedBundleState(t *testing.T, options Options, target destination, record receipt) {
	t.Helper()
	current, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read retained receipt = (%#v, %t, %v)", current, found, err)
	}
	if !equalFiles(current.Files, record.Files) || current.BundleSHA != record.BundleSHA || !sameRuntimes(current.Runtimes, record.Runtimes) {
		t.Fatalf("receipt changed after failed expansion = %#v, want %#v", current, record)
	}
	if err := verifyInstalled(target.path, record.Files); err != nil {
		t.Fatalf("old installed bundle changed after failed expansion: %v", err)
	}
	claims, err := projectedClaims(target, options.Scope, record.Runtimes, skillBundle{files: record.Files}, skillclaim.StateActive, "rollback-check")
	if err != nil {
		t.Fatal(err)
	}
	if err := verifyClaimsUnlocked(filepath.Dir(options.StateRoot), claims); err != nil {
		t.Fatalf("old claims changed after failed expansion: %v", err)
	}
	ciClaimDestination, err := skillclaim.CanonicalDestination(claimDestination(target, "dva-ci"))
	if err != nil {
		t.Fatal(err)
	}
	if _, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), ciClaimDestination); err != nil || found {
		t.Fatalf("new dva-ci claim survived failed expansion = (%t, %v)", found, err)
	}
}

func sameRuntimes(left, right []Runtime) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func sameStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func assertClaimConsumers(t *testing.T, options Options, destination string, want []string) {
	t.Helper()
	for _, name := range bundled.Names {
		claim, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), filepath.Join(destination, name))
		if err != nil {
			t.Fatal(err)
		}
		if !found {
			t.Fatalf("claim for %s is missing", name)
		}
		if !sameStrings(claim.Consumers, want) {
			t.Fatalf("claim %s consumers = %v, want %v", name, claim.Consumers, want)
		}
	}
}

func assertRuntimeStatuses(t *testing.T, got []RuntimeStatus, want map[Runtime]string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("runtime statuses = %v, want %v", got, want)
	}
	for _, status := range got {
		if wantStatus, ok := want[status.Runtime]; !ok || wantStatus != status.Status {
			t.Fatalf("runtime status %s = %s, want %s", status.Runtime, status.Status, wantStatus)
		}
		delete(want, status.Runtime)
	}
	if len(want) != 0 {
		t.Fatalf("missing runtime statuses: %v", want)
	}
}
