package skillinstall

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/ScriptonBasestar/dva/internal/skillclaim"
	bundled "github.com/ScriptonBasestar/dva/skills"
)

func TestRuntimePaths(t *testing.T) {
	t.Parallel()
	home := t.TempDir()
	project := t.TempDir()
	tests := []struct {
		scope   Scope
		runtime Runtime
		want    string
	}{
		{ScopeUser, RuntimeClaudeCode, ".claude/skills"},
		{ScopeUser, RuntimeCodex, ".agents/skills"},
		{ScopeUser, RuntimeOpenCode, ".config/opencode/skills"},
		{ScopeUser, RuntimeAgentMesh, ".config/agent-mesh/skills/dva"},
		{ScopeUser, RuntimeGrok, ".grok/skills"},
		{ScopeUser, RuntimeAntigravity, ".gemini/config/skills"},
		{ScopeProject, RuntimeClaudeCode, ".claude/skills"},
		{ScopeProject, RuntimeCodex, ".agents/skills"},
		{ScopeProject, RuntimeOpenCode, ".opencode/skills"},
		{ScopeProject, RuntimeAgentMesh, ".agent-mesh/skills/dva"},
		{ScopeProject, RuntimeGrok, ".grok/skills"},
		{ScopeProject, RuntimeAntigravity, ".agents/skills"},
	}
	for _, test := range tests {
		t.Run(string(test.scope)+"/"+string(test.runtime), func(t *testing.T) {
			got, err := runtimePath(test.runtime, test.scope, home, project)
			if err != nil {
				t.Fatal(err)
			}
			base := home
			if test.scope == ScopeProject {
				base = project
			}
			if want := filepath.Join(base, test.want); got != want {
				t.Fatalf("path = %q, want %q", got, want)
			}
		})
	}
}

func TestAgentMeshInstallsFlatRenderedSkills(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeAgentMesh)
	result, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := result.Destinations[0].Destination, filepath.Join(options.ProjectRoot, ".agent-mesh", "skills", "dva"); got != want {
		t.Fatalf("destination = %q, want %q", got, want)
	}
	dva, err := os.ReadFile(filepath.Join(result.Destinations[0].Destination, "dva.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"# DVA (Dev Virtual Auto) CLI", "Generated by `dva skill install --runtime agent-mesh`",
		"## Reference: references/commands.md", "## Asset: assets/templates/root-devbox-plan.yml",
		"### DVA Command Reference", "#dva-dva-assets-templates-root-devbox-plan-yml",
	} {
		if !strings.Contains(string(dva), want) {
			t.Errorf("rendered Agent Mesh skill omits %q", want)
		}
	}
	if strings.HasPrefix(string(dva), "---\n") {
		t.Fatal("rendered Agent Mesh skill retained YAML frontmatter")
	}
	if _, err := os.Stat(filepath.Join(result.Destinations[0].Destination, "dva-ci.md")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(result.Destinations[0].Destination, "dva", "SKILL.md")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Agent Mesh install created native skill directory: %v", err)
	}
	for _, name := range bundled.Names {
		claim, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), filepath.Join(result.Destinations[0].Destination, name+".md"))
		if err != nil || !found {
			t.Fatalf("Agent Mesh claim %s = (%#v, %t, %v)", name, claim, found, err)
		}
		if claim.Name != name || claim.Kind != skillclaim.KindFile || len(claim.Files) != 1 || claim.Files[0].Path != "." {
			t.Fatalf("Agent Mesh claim %s has native semantics: %#v", name, claim)
		}
	}

	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "installed" {
		t.Fatalf("status = %s", status.Destinations[0].Status)
	}
	if _, err := Uninstall(options); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(result.Destinations[0].Destination); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("Agent Mesh DVA namespace remains after uninstall: %v", err)
	}
}

func TestRestoreTakeoverBacksUpAndExplicitRestoreReturnsExactTree(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeCodex)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(destinations[0].path, "dva")
	empty := filepath.Join(foreign, "nested", "empty")
	if err := os.MkdirAll(empty, 0o711); err != nil {
		t.Fatal(err)
	}
	original := filepath.Join(foreign, "nested", "original.txt")
	if err := os.WriteFile(original, []byte("exact original"), 0o640); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err == nil {
		t.Fatal("receipt-less collision installed without takeover")
	}
	options.Takeover = true
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if installed.Destinations[0].BackupStatus != "available" {
		t.Fatalf("backup status = %q", installed.Destinations[0].BackupStatus)
	}
	if _, err := os.Stat(original); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("foreign tree remains after takeover: %v", err)
	}
	options.Takeover = false
	if _, err := Uninstall(options); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(original); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("ordinary uninstall restored the original automatically: %v", err)
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "backup-only" || status.Destinations[0].BackupStatus != "available" {
		t.Fatalf("backup-only status = %#v", status.Destinations[0])
	}
	options.RestoreTakeoverBackup = true
	if _, err := Uninstall(options); err != nil {
		t.Fatal(err)
	}
	contents, err := os.ReadFile(original)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "exact original" {
		t.Fatalf("restored contents = %q", contents)
	}
	info, err := os.Stat(original)
	if err != nil || info.Mode().Perm() != 0o640 {
		t.Fatalf("restored file mode = %v, err=%v", info, err)
	}
	info, err = os.Stat(empty)
	if err != nil || !info.IsDir() || info.Mode().Perm() != 0o711 {
		t.Fatalf("empty directory was not restored exactly: %v, err=%v", info, err)
	}
}

func TestTakeoverRefusesOtherProducerClaim(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeCodex)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(destinations[0].path, "dva")
	if err := os.MkdirAll(path, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(path, "SKILL.md"), []byte("foreign"), 0o600); err != nil {
		t.Fatal(err)
	}
	// A well-formed foreign claim is the authoritative refusal signal.
	claimRoot := filepath.Dir(options.StateRoot)
	canonical, err := skillclaim.CanonicalDestination(path)
	if err != nil {
		t.Fatal(err)
	}
	files := []skillclaim.FileHash{{Path: "SKILL.md", SHA: strings.Repeat("0", sha256.Size*2)}}
	sourceDigest, err := skillclaim.ManifestDigest(files)
	if err != nil {
		t.Fatal(err)
	}
	claim := skillclaim.Claim{Schema: skillclaim.Schema, Name: "dva", Kind: skillclaim.KindDirectory, State: skillclaim.StateReserved, OperationID: "foreign-test", Generation: 1, Destination: canonical, Producer: "other", Format: "agent-skills-directory", Scope: "user", Consumers: []string{"codex"}, SourceDigest: sourceDigest, Files: files}
	store, err := skillclaim.Begin(claimRoot, []string{canonical})
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Reserve(claim); err != nil {
		t.Fatal(err)
	}
	previous, err := skillclaim.Digest(claim)
	if err != nil {
		t.Fatal(err)
	}
	claim.State, claim.Generation = skillclaim.StateActive, 2
	if err := store.CompareAndSwap(claim, 1, previous); err != nil {
		t.Fatal(err)
	}
	if err := store.Close(); err != nil {
		t.Fatal(err)
	}
	options.Takeover = true
	if _, err := Install(options); err == nil {
		t.Fatal("takeover accepted other producer claim")
	}
}

func TestCorruptTakeoverBackupBlocksRestore(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeCodex)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(destinations[0].path, "dva")
	if err := os.MkdirAll(foreign, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(foreign, "marker"), []byte("foreign"), 0o600); err != nil {
		t.Fatal(err)
	}
	options.Takeover = true
	if _, err := Install(options); err != nil {
		t.Fatal(err)
	}
	record, found, err := readReceipt(receiptPath(options.StateRoot, destinations[0].path))
	if err != nil || !found || len(record.Takeovers) == 0 {
		t.Fatalf("takeover receipt = (%#v, %t, %v)", record, found, err)
	}
	backup, err := takeoverBackupPath(options.StateRoot, record.Destination, record.Takeovers[0])
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(filepath.Join(backup, "marker"), 0o644); err != nil {
		t.Fatal(err)
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].BackupStatus != "corrupt" {
		t.Fatalf("corrupt backup status = %#v", status.Destinations[0])
	}
	options.Takeover, options.RestoreTakeoverBackup = false, true
	if _, err := Uninstall(options); err == nil {
		t.Fatal("restore accepted corrupt takeover backup")
	}
}

func TestRestoreRejectsIncompleteBackupInventory(t *testing.T) {
	for _, test := range []struct {
		name   string
		mutate func(t *testing.T, options Options, target destination, record *receipt)
	}{
		{
			name: "omitted receipt record",
			mutate: func(t *testing.T, options Options, target destination, record *receipt) {
				t.Helper()
				record.Takeovers = append([]takeoverBackup(nil), record.Takeovers[:1]...)
				if err := writeReceipt(receiptPath(options.StateRoot, target.path), *record); err != nil {
					t.Fatal(err)
				}
			},
		},
		{
			name: "extra backup sibling",
			mutate: func(t *testing.T, options Options, target destination, record *receipt) {
				t.Helper()
				path, err := takeoverBackupPath(options.StateRoot, record.Destination, record.Takeovers[0])
				if err != nil {
					t.Fatal(err)
				}
				if err := os.Mkdir(filepath.Join(filepath.Dir(path), "unlisted"), 0o700); err != nil {
					t.Fatal(err)
				}
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			options := testOptions(t, ScopeProject, RuntimeCodex)
			_, targets, err := resolve(options)
			if err != nil {
				t.Fatal(err)
			}
			target := targets[0]
			for _, name := range []string{"dva", "dva-config"} {
				root := filepath.Join(target.path, name)
				if err := os.MkdirAll(root, 0o750); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(root, "original.txt"), []byte("foreign-"+name), 0o640); err != nil {
					t.Fatal(err)
				}
			}
			options.Takeover = true
			if _, err := Install(options); err != nil {
				t.Fatal(err)
			}
			record, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
			if err != nil || !found || len(record.Takeovers) != 2 {
				t.Fatalf("takeover receipt = (%#v, %t, %v)", record, found, err)
			}
			backupRoot := filepath.Join(takeoverDestinationRoot(options.StateRoot, record.Destination), record.Takeovers[0].BackupID)
			test.mutate(t, options, target, &record)
			options.Takeover, options.RestoreTakeoverBackup = false, true
			if _, err := Uninstall(options); err == nil {
				t.Fatal("restore accepted incomplete backup inventory")
			}
			if _, err := os.Stat(filepath.Join(target.path, "dva", "SKILL.md")); err != nil {
				t.Fatalf("failed restore changed installed DVA skill: %v", err)
			}
			if _, err := os.Stat(filepath.Join(backupRoot, "dva-config", "original.txt")); err != nil {
				t.Fatalf("failed restore deleted unlisted original: %v", err)
			}
		})
	}
}

func TestTakeoverBackupCapturesLiveEntryBeforeReplacement(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	_, targets, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	target := targets[0]
	if err := ensureDestination(target.path); err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(target.path, "dva")
	if err := os.MkdirAll(foreign, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(foreign, "original"), []byte("exact foreign bytes"), 0o640); err != nil {
		t.Fatal(err)
	}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	records, rollback, _, cleanup, recovery, err := createTakeoverBackups(options.StateRoot, target, bundle)
	if err != nil {
		t.Fatal(err)
	}
	if len(records) != 1 || records[0].Skill != "dva" {
		t.Fatalf("captured takeover records = %#v", records)
	}
	if _, err := os.Lstat(foreign); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("foreign entry was not atomically captured: %v", err)
	}
	backup, err := os.ReadFile(filepath.Join(recovery, "dva", "original"))
	if err != nil || string(backup) != "exact foreign bytes" {
		t.Fatalf("durable snapshot = %q, %v", backup, err)
	}
	if err := rollback(); err != nil {
		t.Fatal(err)
	}
	restored, err := os.ReadFile(filepath.Join(foreign, "original"))
	if err != nil || string(restored) != "exact foreign bytes" {
		t.Fatalf("restored original = %q, %v", restored, err)
	}
	if err := cleanup(); err != nil {
		t.Fatal(err)
	}
}

func TestTakeoverRollbackCollisionRetainsDurableRecoveryArtifact(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	_, targets, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	target := targets[0]
	if err := ensureDestination(target.path); err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(target.path, "dva")
	if err := os.MkdirAll(foreign, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(foreign, "original"), []byte("recover me"), 0o600); err != nil {
		t.Fatal(err)
	}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	_, rollback, _, _, recovery, err := createTakeoverBackups(options.StateRoot, target, bundle)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(foreign, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := rollback(); err == nil {
		t.Fatal("rollback accepted a late collision")
	}
	contents, err := os.ReadFile(filepath.Join(recovery, "dva", "original"))
	if err != nil || string(contents) != "recover me" {
		t.Fatalf("recovery artifact = %q, %v", contents, err)
	}
}

func TestClaimRollbackRestoresActiveSetAfterPartialRelease(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: options.Runtimes}
	record, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatal(err)
	}
	bundle := skillBundle{files: record.Files}
	paths, err := claimDestinations(target, bundle)
	if err != nil {
		t.Fatal(err)
	}
	store, err := skillclaim.Begin(filepath.Dir(options.StateRoot), paths)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = store.Close() }()
	projection, err := projectedClaims(target, options.Scope, record.Runtimes, bundle, skillclaim.StateActive, "rollback-test")
	if err != nil {
		t.Fatal(err)
	}
	current, err := readLockedClaims(store, projection)
	if err != nil {
		t.Fatal(err)
	}
	releasing, err := transitionActiveClaims(store, current, current, skillclaim.StateReleasing, "partial-release")
	if err != nil {
		t.Fatal(err)
	}
	previous, err := skillclaim.Digest(releasing[0])
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Remove(releasing[0].Destination, releasing[0].Producer, releasing[0].OperationID, releasing[0].Generation, previous); err != nil {
		t.Fatal(err)
	}
	if err := rollbackClaimsToActive(store, current); err != nil {
		t.Fatal(err)
	}
	restored, err := readLockedClaims(store, projection)
	if err != nil {
		t.Fatal(err)
	}
	if err := verifyActiveClaims(restored, projection); err != nil {
		t.Fatal(err)
	}
}

func TestClaimRollbackRemovesPartialTemporaryRestoreSet(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	_, targets, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	target := targets[0]
	if err := ensureDestination(target.path); err != nil {
		t.Fatal(err)
	}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	paths, err := claimDestinations(target, bundle)
	if err != nil {
		t.Fatal(err)
	}
	store, err := skillclaim.Begin(filepath.Dir(options.StateRoot), paths)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = store.Close() }()
	reserved, err := projectedClaims(target, options.Scope, options.Runtimes, bundle, skillclaim.StateReserved, "temporary-restore")
	if err != nil {
		t.Fatal(err)
	}
	reserved, err = reserveClaims(store, reserved)
	if err != nil {
		t.Fatal(err)
	}
	active, err := activateReservedClaims(store, reserved)
	if err != nil {
		t.Fatal(err)
	}
	restoring, err := transitionActiveClaims(store, active, active, skillclaim.StateRestoring, "temporary-restore-mutation")
	if err != nil {
		t.Fatal(err)
	}
	previous, err := skillclaim.Digest(restoring[0])
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Remove(restoring[0].Destination, restoring[0].Producer, restoring[0].OperationID, restoring[0].Generation, previous); err != nil {
		t.Fatal(err)
	}
	if err := rollbackClaimsToAbsent(store, restoring); err != nil {
		t.Fatal(err)
	}
	if err := ensureClaimsAbsent(store, reserved); err != nil {
		t.Fatal(err)
	}
}

func TestAgentMeshRendererInlinesAssetsAndDemotesReferenceHeadings(t *testing.T) {
	t.Parallel()
	contents, err := renderAgentMeshSkill("dva")
	if err != nil {
		t.Fatal(err)
	}
	rendered := string(contents)
	for _, path := range []string{
		"assets/templates/migrate-modes-to-plans.yml", "assets/templates/root-devbox-plan.yml", "assets/templates/subproject-local.yml",
		"references/advanced.md", "references/commands.md", "references/operation-safety.md", "references/patterns.md",
	} {
		if !strings.Contains(rendered, "## "+map[bool]string{true: "Asset", false: "Reference"}[strings.HasPrefix(path, "assets/")]+": "+path) {
			t.Errorf("rendered skill omits inlined %s", path)
		}
	}
	if strings.Contains(rendered, "\n# DVA Command Reference\n") {
		t.Fatal("inlined reference retained an H1 above its Reference parent")
	}
	if !strings.Contains(rendered, "[assets/templates/root-devbox-plan.yml](#dva-dva-assets-templates-root-devbox-plan-yml)") {
		t.Fatal("local resource index did not expose the inlined asset anchor")
	}
	if strings.Contains(rendered, "`[inline ") {
		t.Fatal("renderer produced an inert Markdown link inside inline code")
	}
	if !strings.Contains(rendered, "```yaml\n# dva.yml") {
		t.Fatal("renderer changed a fenced YAML comment")
	}
}

func TestReceiptRejectsCrossFormatFilesBeforeStatusOrUninstall(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeClaudeCode)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destinations[0]
	if err := os.MkdirAll(target.path, 0o755); err != nil {
		t.Fatal(err)
	}
	flat := filepath.Join(target.path, "dva.md")
	if err := os.WriteFile(flat, []byte("foreign flat skill"), 0o644); err != nil {
		t.Fatal(err)
	}
	record := receipt{
		Schema: 1, Scope: options.Scope, Destination: target.path, Runtimes: target.runtimes,
		Version: "test", BundleSHA: strings.Repeat("0", sha256.Size*2),
		Files: []fileHash{{Path: "dva.md", SHA: strings.Repeat("0", sha256.Size*2)}},
	}
	if err := writeReceipt(receiptPath(options.StateRoot, target.path), record); err != nil {
		t.Fatal(err)
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "invalid-receipt" {
		t.Fatalf("status = %s, want invalid-receipt", status.Destinations[0].Status)
	}
	if _, err := Uninstall(options); err == nil {
		t.Fatal("uninstall accepted a native receipt with flat files")
	}
	if _, err := os.Stat(flat); err != nil {
		t.Fatalf("uninstall removed foreign flat file after receipt rejection: %v", err)
	}
}

func TestReceiptDecoderFailsClosedOnAmbiguousOrUnsafeFiles(t *testing.T) {
	mutations := map[string]func(t *testing.T, path string, contents []byte){
		"duplicate-key": func(t *testing.T, path string, contents []byte) {
			t.Helper()
			contents = bytes.Replace(contents, []byte(`"schema": 3,`), []byte(`"schema": 3, "schema": 3,`), 1)
			if err := os.WriteFile(path, contents, 0o600); err != nil {
				t.Fatal(err)
			}
		},
		"unknown-field": func(t *testing.T, path string, contents []byte) {
			t.Helper()
			contents = bytes.Replace(contents, []byte("{\n"), []byte("{\n  \"unknown\": true,\n"), 1)
			if err := os.WriteFile(path, contents, 0o600); err != nil {
				t.Fatal(err)
			}
		},
		"trailing-json": func(t *testing.T, path string, contents []byte) {
			t.Helper()
			if err := os.WriteFile(path, append(contents, []byte("{}\n")...), 0o600); err != nil {
				t.Fatal(err)
			}
		},
		"loose-mode": func(t *testing.T, path string, _ []byte) {
			t.Helper()
			if err := os.Chmod(path, 0o644); err != nil {
				t.Fatal(err)
			}
		},
		"symlink": func(t *testing.T, path string, contents []byte) {
			t.Helper()
			target := path + ".foreign"
			if err := os.WriteFile(target, contents, 0o600); err != nil {
				t.Fatal(err)
			}
			if err := os.Remove(path); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(target, path); err != nil {
				t.Fatal(err)
			}
		},
	}
	for name, mutate := range mutations {
		t.Run(name, func(t *testing.T) {
			options := testOptions(t, ScopeProject, RuntimeCodex)
			installed, err := Install(options)
			if err != nil {
				t.Fatal(err)
			}
			path := receiptPath(options.StateRoot, installed.Destinations[0].Destination)
			contents, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			mutate(t, path, contents)
			status, err := Status(options)
			if err != nil {
				t.Fatal(err)
			}
			if status.Destinations[0].Status != "invalid-receipt" {
				t.Fatalf("unsafe receipt status = %s", status.Destinations[0].Status)
			}
			if _, err := Uninstall(options); err == nil {
				t.Fatal("unsafe receipt was accepted for uninstall")
			}
		})
	}
}

func TestLegacyNativeReceiptRemainsReadable(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeGrok)
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: []Runtime{RuntimeGrok}}
	receiptFile := receiptPath(options.StateRoot, target.path)
	record, found, err := readReceipt(receiptFile)
	if err != nil || !found {
		t.Fatalf("read current receipt = (%v, %t, %v)", record, found, err)
	}
	record.Schema, record.Format = 1, ""
	record.Files = withoutCISkill(record.Files)
	record.BundleSHA = sourceBundleSHA(record.Files)
	if err := os.RemoveAll(filepath.Join(target.path, "dva-ci")); err != nil {
		t.Fatal(err)
	}
	ciClaimDestination, err := skillclaim.CanonicalDestination(filepath.Join(target.path, "dva-ci"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), ciClaimDestination)); err != nil {
		t.Fatal(err)
	}
	if err := writeReceipt(receiptFile, record); err != nil {
		t.Fatal(err)
	}
	claims, err := projectedClaims(target, options.Scope, record.Runtimes, skillBundle{files: record.Files}, skillclaim.StateActive, "legacy-test")
	if err != nil {
		t.Fatal(err)
	}
	for _, claim := range claims {
		if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), claim.Destination)); err != nil {
			t.Fatal(err)
		}
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "legacy-unclaimed" {
		t.Fatalf("legacy native receipt status = %s", status.Destinations[0].Status)
	}
	if _, err := Install(options); err != nil {
		t.Fatalf("migrate legacy receipt during install: %v", err)
	}
	if _, err := os.Stat(filepath.Join(target.path, "dva-ci", "SKILL.md")); err != nil {
		t.Fatalf("migration did not add bundled CI skill: %v", err)
	}
	migrated, found, err := readReceipt(receiptFile)
	if err != nil || !found || migrated.Schema != receiptSchemaCurrent || migrated.Installation != "active" {
		t.Fatalf("migrated receipt = (%#v, %t, %v)", migrated, found, err)
	}
	assertClaimConsumers(t, options, target.path, []string{"grok"})
}

func TestClaimedBundleUpgradeAddsNewSkill(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)

	result, err := Install(options)
	if err != nil {
		t.Fatalf("expand claimed bundle: %v", err)
	}
	if result.Destinations[0].Status != "installed" {
		t.Fatalf("expanded bundle status = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(filepath.Join(target.path, "dva-ci", "SKILL.md")); err != nil {
		t.Fatalf("expanded bundle did not install dva-ci: %v", err)
	}
	updated, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read expanded receipt = (%#v, %t, %v)", updated, found, err)
	}
	if len(updated.Files) <= len(oldReceipt.Files) || !containsSkillFiles(updated.Files, "dva-ci") {
		t.Fatalf("expanded receipt files do not include dva-ci: %v", updated.Files)
	}
	assertClaimConsumers(t, options, target.path, []string{"grok"})
}

func TestClaimedFlatBundleUpgradeAddsNewSkill(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeAgentMesh)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)

	if _, err := Install(options); err != nil {
		t.Fatalf("expand claimed flat bundle: %v", err)
	}
	if _, err := os.Stat(claimDestination(target, "dva-ci")); err != nil {
		t.Fatalf("expanded flat bundle did not install dva-ci: %v", err)
	}
	updated, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read expanded flat receipt = (%#v, %t, %v)", updated, found, err)
	}
	if len(updated.Files) <= len(oldReceipt.Files) || !containsSkillFiles(updated.Files, "dva-ci") {
		t.Fatalf("expanded flat receipt files do not include dva-ci: %v", updated.Files)
	}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	claims, err := projectedClaims(target, options.Scope, options.Runtimes, bundle, skillclaim.StateActive, "flat-upgrade-check")
	if err != nil {
		t.Fatal(err)
	}
	if err := verifyClaimsUnlocked(filepath.Dir(options.StateRoot), claims); err != nil {
		t.Fatalf("expanded flat bundle claims: %v", err)
	}
}

func TestClaimedBundleUpgradeRefusesForeignNewSkillCollision(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)
	foreign := filepath.Join(target.path, "dva-ci", "foreign-marker")
	if err := os.MkdirAll(filepath.Dir(foreign), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(foreign, []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := Install(options); err == nil || !strings.Contains(err.Error(), "newly bundled DVA skill") {
		t.Fatalf("claimed expansion accepted foreign dva-ci collision: %v", err)
	}
	contents, err := os.ReadFile(foreign)
	if err != nil || string(contents) != "foreign" {
		t.Fatalf("foreign collision changed = %q, %v", contents, err)
	}
	assertClaimedBundleState(t, options, target, oldReceipt)
}

func TestClaimedBundleUpgradeRollsBackAfterReceiptFailure(t *testing.T) {
	t.Parallel()
	if runtime.GOOS == "windows" {
		t.Skip("directory permission failure injection is not portable to Windows")
	}
	options := testOptions(t, ScopeUser, RuntimeGrok)
	target, oldReceipt := reduceClaimedBundleToTwoSkills(t, options)
	receiptDir := filepath.Dir(receiptPath(options.StateRoot, target.path))
	if err := os.Chmod(receiptDir, 0o500); err != nil {
		t.Skipf("cannot make receipt directory read-only: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(receiptDir, 0o755) })
	probe, probeErr := os.CreateTemp(receiptDir, ".permission-probe-")
	if probeErr == nil {
		_ = probe.Close()
		_ = os.Remove(probe.Name())
		_ = os.Chmod(receiptDir, 0o755)
		t.Skip("cannot enforce receipt directory write failure in this environment")
	}
	_, err := Install(options)
	if restoreErr := os.Chmod(receiptDir, 0o755); restoreErr != nil {
		t.Fatal(restoreErr)
	}
	if err == nil || !strings.Contains(err.Error(), "update receipt") {
		t.Fatalf("claimed expansion succeeded despite receipt failure: %v", err)
	}
	assertClaimedBundleState(t, options, target, oldReceipt)
	if _, err := os.Stat(filepath.Join(target.path, "dva-ci")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("rollback left new skill behind: %v", err)
	}
}

func TestLegacyAbsentRuntimeUninstallDoesNotCreateClaims(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: options.Runtimes}
	receiptFile := receiptPath(options.StateRoot, target.path)
	record, found, err := readReceipt(receiptFile)
	if err != nil || !found {
		t.Fatalf("read current receipt = (%v, %t, %v)", record, found, err)
	}
	record.Schema, record.Format = 1, ""
	if err := writeReceipt(receiptFile, record); err != nil {
		t.Fatal(err)
	}
	claims, err := projectedClaims(target, options.Scope, record.Runtimes, skillBundle{files: record.Files}, skillclaim.StateActive, "legacy-absent")
	if err != nil {
		t.Fatal(err)
	}
	for _, claim := range claims {
		if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), claim.Destination)); err != nil {
			t.Fatal(err)
		}
	}
	absent := options
	absent.Runtimes = []Runtime{RuntimeAntigravity}
	result, err := Uninstall(absent)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "not-installed" {
		t.Fatalf("absent runtime uninstall = %s", result.Destinations[0].Status)
	}
	for _, claim := range claims {
		if _, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), claim.Destination); err != nil || found {
			t.Fatalf("absent runtime created claim = (%t, %v)", found, err)
		}
	}
	status, err := Status(options)
	if err != nil || status.Destinations[0].Status != "legacy-unclaimed" {
		t.Fatalf("legacy owner status = %#v, %v", status, err)
	}
}

func TestUpToDateInstallStillAcquiresClaimLocks(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: options.Runtimes}
	bundle, err := bundleFor(target)
	if err != nil {
		t.Fatal(err)
	}
	paths, err := claimDestinations(target, bundle)
	if err != nil {
		t.Fatal(err)
	}
	locks, err := skillclaim.AcquireLocks(filepath.Dir(options.StateRoot), paths)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = locks.Release() }()
	if _, err := Install(options); err == nil || !strings.Contains(err.Error(), "claim mutation lock exists") {
		t.Fatalf("up-to-date install bypassed claim locks: %v", err)
	}
}

func TestAgentMeshKeepsForeignNamespaceFilesAndDetectsDVAFileCollision(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeAgentMesh)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	destination := destinations[0].path
	if err := os.MkdirAll(destination, 0o755); err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(destination, "other.md")
	if err := os.WriteFile(foreign, []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err != nil {
		t.Fatal(err)
	}
	if _, err := Uninstall(options); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Fatalf("uninstall removed foreign Agent Mesh file: %v", err)
	}
	if err := os.WriteFile(filepath.Join(destination, "dva.md"), []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err == nil {
		t.Fatal("Agent Mesh DVA filename collision was overwritten")
	}
}

func TestMixedAgentMeshInstallPreflightsBeforeMutation(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeAgentMesh, RuntimeClaudeCode)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	last := destinations[len(destinations)-1]
	if err := os.MkdirAll(filepath.Join(last.path, "dva"), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err == nil {
		t.Fatal("mixed install ignored a later collision")
	}
	for _, target := range destinations[:len(destinations)-1] {
		if _, err := os.Stat(filepath.Join(target.path, "dva.md")); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("earlier destination mutated before collision: %v", err)
		}
	}
}

func TestProjectDeduplicatesSharedAgentsDestination(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex, RuntimeAntigravity)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	if len(destinations) != 1 {
		t.Fatalf("destinations = %d, want 1", len(destinations))
	}
	if got, want := destinations[0].runtimes, []Runtime{RuntimeAntigravity, RuntimeCodex}; !sameRuntimes(got, want) {
		t.Fatalf("runtimes = %v, want %v", got, want)
	}
}

func TestRiskySkillOperationsRequireExplicitRuntime(t *testing.T) {
	t.Parallel()
	for _, options := range []Options{
		{Scope: ScopeUser, HomeDir: t.TempDir(), ProjectRoot: t.TempDir(), StateRoot: filepath.Join(t.TempDir(), "dva"), Takeover: true},
		{Scope: ScopeUser, HomeDir: t.TempDir(), ProjectRoot: t.TempDir(), StateRoot: filepath.Join(t.TempDir(), "dva"), RestoreTakeoverBackup: true},
	} {
		if _, _, err := resolve(options); err == nil {
			t.Fatal("risky skill operation accepted implicit all-runtime selection")
		}
	}
}

func TestTakeoverDryRunDoesNotCreateClaimReceiptOrBackup(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeCodex)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	foreign := filepath.Join(destinations[0].path, "dva")
	if err := os.MkdirAll(foreign, 0o755); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(foreign, "marker")
	if err := os.WriteFile(marker, []byte("foreign"), 0o640); err != nil {
		t.Fatal(err)
	}
	options.Takeover, options.DryRun = true, true
	result, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].BackupStatus != "would-backup" {
		t.Fatalf("dry-run backup status = %q", result.Destinations[0].BackupStatus)
	}
	contents, err := os.ReadFile(marker)
	if err != nil || string(contents) != "foreign" {
		t.Fatalf("dry-run changed foreign marker: %q, %v", contents, err)
	}
	if _, err := os.Stat(options.StateRoot); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("dry-run created DVA state: %v", err)
	}
	if _, err := os.Stat(filepath.Join(filepath.Dir(options.StateRoot), "agent-skills")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("dry-run created neutral claims: %v", err)
	}
}

func TestEmbeddedSkillsContainCanonicalFiles(t *testing.T) {
	t.Parallel()
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate test source")
	}
	repoSkills := filepath.Join(filepath.Dir(sourceFile), "..", "..", "skills")
	var embeddedPaths []string
	if err := fs.WalkDir(bundled.Files, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() || path == "embed.go" {
			return err
		}
		embeddedPaths = append(embeddedPaths, path)
		embedded, err := fs.ReadFile(bundled.Files, path)
		if err != nil {
			return err
		}
		disk, err := os.ReadFile(filepath.Join(repoSkills, filepath.FromSlash(path)))
		if err != nil {
			return err
		}
		if !bytes.Equal(embedded, disk) {
			t.Errorf("embedded %s differs from canonical disk source", path)
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	var diskPaths []string
	for _, name := range bundled.Names {
		if err := filepath.WalkDir(filepath.Join(repoSkills, name), func(path string, entry fs.DirEntry, err error) error {
			if err != nil || entry.IsDir() {
				return err
			}
			relative, err := filepath.Rel(repoSkills, path)
			if err != nil {
				return err
			}
			diskPaths = append(diskPaths, filepath.ToSlash(relative))
			return nil
		}); err != nil {
			t.Fatal(err)
		}
	}
	sort.Strings(embeddedPaths)
	sort.Strings(diskPaths)
	if !sameStrings(embeddedPaths, diskPaths) {
		t.Fatalf("embedded file inventory differs\nembedded: %v\ndisk: %v", embeddedPaths, diskPaths)
	}
}

func TestInstallStatusAndUninstallSharedDestination(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex, RuntimeAntigravity)
	result, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Destinations) != 1 || result.Destinations[0].Status != "installed" {
		t.Fatalf("install result = %#v", result)
	}
	destination := result.Destinations[0].Destination
	if _, err := os.Stat(filepath.Join(destination, "dva", "SKILL.md")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva-config", "references", "diagnosis.md")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva-ci", "SKILL.md")); err != nil {
		t.Fatal(err)
	}
	result, err = Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "up-to-date" {
		t.Fatalf("second install = %s", result.Destinations[0].Status)
	}
	result, err = Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "installed" {
		t.Fatalf("status = %s", result.Destinations[0].Status)
	}
	assertClaimConsumers(t, options, destination, []string{"antigravity", "codex"})

	codexOnly := options
	codexOnly.Runtimes = []Runtime{RuntimeCodex}
	result, err = Uninstall(codexOnly)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "unlinked" {
		t.Fatalf("partial uninstall = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva")); err != nil {
		t.Fatalf("shared skill was removed: %v", err)
	}
	assertClaimConsumers(t, options, destination, []string{"antigravity"})
	antigravityOnly := options
	antigravityOnly.Runtimes = []Runtime{RuntimeAntigravity}
	result, err = Uninstall(antigravityOnly)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "uninstalled" {
		t.Fatalf("last uninstall = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("skill remains after uninstall: %v", err)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva-ci")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("CI skill remains after uninstall: %v", err)
	}
}

func TestSharedDestinationReportsEachRuntimeState(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	if _, err := Install(options); err != nil {
		t.Fatal(err)
	}

	both := options
	both.Runtimes = []Runtime{RuntimeCodex, RuntimeAntigravity}
	status, err := Status(both)
	if err != nil {
		t.Fatal(err)
	}
	entry := status.Destinations[0]
	if entry.Status != "partial" {
		t.Fatalf("aggregate status = %s, want partial", entry.Status)
	}
	assertRuntimeStatuses(t, entry.RuntimeStatuses, map[Runtime]string{
		RuntimeCodex: "installed", RuntimeAntigravity: "absent",
	})

	antigravityOnly := options
	antigravityOnly.Runtimes = []Runtime{RuntimeAntigravity}
	result, err := Uninstall(antigravityOnly)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "not-installed" {
		t.Fatalf("absent runtime uninstall = %s", result.Destinations[0].Status)
	}
	status, err = Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "installed" {
		t.Fatalf("codex changed by absent runtime uninstall: %s", status.Destinations[0].Status)
	}
}

func TestDryRunDoesNotMutate(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeClaudeCode)
	options.DryRun = true
	result, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "would-install" {
		t.Fatalf("status = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(result.Destinations[0].Destination); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("dry-run created destination: %v", err)
	}
	if _, err := os.Stat(options.StateRoot); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("dry-run created state: %v", err)
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "absent" {
		t.Fatalf("status after dry-run = %s", status.Destinations[0].Status)
	}
}

func TestAbsentUninstallDryRunDoesNotCreateClaimState(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeCodex)
	options.DryRun = true
	result, err := Uninstall(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "not-installed" {
		t.Fatalf("absent uninstall dry-run = %s", result.Destinations[0].Status)
	}
	if _, err := os.Lstat(filepath.Join(filepath.Dir(options.StateRoot), "agent-skills")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("absent uninstall dry-run created persistent state: %v", err)
	}
	if _, err := os.Lstat(options.ProjectRoot); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("absent uninstall dry-run created project state: %v", err)
	}
}

func TestUninstallDryRunDoesNotMutate(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeClaudeCode)
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	destination := installed.Destinations[0].Destination
	receiptFile := receiptPath(options.StateRoot, destination)
	receiptBefore, err := os.ReadFile(receiptFile)
	if err != nil {
		t.Fatal(err)
	}
	options.DryRun = true
	result, err := Uninstall(options)
	if err != nil {
		t.Fatal(err)
	}
	if result.Destinations[0].Status != "would-uninstall" {
		t.Fatalf("status = %s", result.Destinations[0].Status)
	}
	if _, err := os.Stat(filepath.Join(destination, "dva", "SKILL.md")); err != nil {
		t.Fatalf("dry-run removed skill: %v", err)
	}
	receiptAfter, err := os.ReadFile(receiptFile)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(receiptBefore, receiptAfter) {
		t.Fatal("dry-run changed receipt")
	}
}

func TestCollisionAndDriftAreRefused(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeGrok)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	collision := filepath.Join(destinations[0].path, "dva")
	if err := os.MkdirAll(collision, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err == nil {
		t.Fatal("collision install succeeded")
	}
	if err := os.RemoveAll(collision); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(destinations[0].path, "dva", "SKILL.md"), []byte("changed"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Uninstall(options); err == nil {
		t.Fatal("drifted uninstall succeeded")
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "drifted" {
		t.Fatalf("status = %s", status.Destinations[0].Status)
	}
}

func TestMultiDestinationOperationsPreflightBeforeMutation(t *testing.T) {
	t.Parallel()
	t.Run("install collision", func(t *testing.T) {
		options := testOptions(t, ScopeProject, RuntimeClaudeCode, RuntimeGrok)
		_, destinations, err := resolve(options)
		if err != nil {
			t.Fatal(err)
		}
		if len(destinations) != 2 {
			t.Fatalf("destinations = %v", destinations)
		}
		laterCollision := filepath.Join(destinations[1].path, "dva")
		if err := os.MkdirAll(laterCollision, 0o755); err != nil {
			t.Fatal(err)
		}
		if _, err := Install(options); err == nil {
			t.Fatal("multi-destination install ignored later collision")
		}
		if _, err := os.Stat(filepath.Join(destinations[0].path, "dva")); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("earlier destination mutated before collision: %v", err)
		}
	})

	t.Run("uninstall drift", func(t *testing.T) {
		options := testOptions(t, ScopeProject, RuntimeClaudeCode, RuntimeGrok)
		installed, err := Install(options)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(installed.Destinations[1].Destination, "dva", "SKILL.md"), []byte("drift"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := Uninstall(options); err == nil {
			t.Fatal("multi-destination uninstall ignored later drift")
		}
		if _, err := os.Stat(filepath.Join(installed.Destinations[0].Destination, "dva", "SKILL.md")); err != nil {
			t.Fatalf("earlier destination removed before drift was found: %v", err)
		}
	})

	t.Run("claimed bundle expansion collision", func(t *testing.T) {
		options := testOptions(t, ScopeProject, RuntimeClaudeCode, RuntimeGrok)
		_, destinations, err := resolve(options)
		if err != nil {
			t.Fatal(err)
		}
		if len(destinations) != 2 {
			t.Fatalf("destinations = %v", destinations)
		}
		if _, err := Install(options); err != nil {
			t.Fatal(err)
		}
		records := make(map[string]receipt, len(destinations))
		for _, target := range destinations {
			records[target.path] = reduceClaimedBundleAtTarget(t, options, target)
		}
		laterCollision := filepath.Join(claimDestination(destinations[1], "dva-ci"), "foreign-marker")
		if err := os.MkdirAll(filepath.Dir(laterCollision), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(laterCollision, []byte("foreign"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := Install(options); err == nil || !strings.Contains(err.Error(), "newly bundled DVA skill") {
			t.Fatalf("multi-destination claimed expansion ignored later collision: %v", err)
		}
		assertClaimedBundleState(t, options, destinations[0], records[destinations[0].path])
		if _, err := os.Stat(claimDestination(destinations[0], "dva-ci")); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("earlier claimed destination upgraded before later collision: %v", err)
		}
	})

	t.Run("legacy bundle expansion collision", func(t *testing.T) {
		options := testOptions(t, ScopeProject, RuntimeClaudeCode, RuntimeGrok)
		_, destinations, err := resolve(options)
		if err != nil {
			t.Fatal(err)
		}
		if len(destinations) != 2 {
			t.Fatalf("destinations = %v", destinations)
		}
		if _, err := Install(options); err != nil {
			t.Fatal(err)
		}
		for _, target := range destinations {
			record := reduceClaimedBundleAtTarget(t, options, target)
			record.Schema, record.Format = 1, ""
			if err := writeReceipt(receiptPath(options.StateRoot, target.path), record); err != nil {
				t.Fatal(err)
			}
			claims, err := projectedClaims(target, options.Scope, record.Runtimes, skillBundle{files: record.Files}, skillclaim.StateActive, "legacy-preflight")
			if err != nil {
				t.Fatal(err)
			}
			for _, claim := range claims {
				if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), claim.Destination)); err != nil {
					t.Fatal(err)
				}
			}
		}
		laterCollision := filepath.Join(claimDestination(destinations[1], "dva-ci"), "foreign-marker")
		if err := os.MkdirAll(filepath.Dir(laterCollision), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(laterCollision, []byte("foreign"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := Install(options); err == nil || !strings.Contains(err.Error(), "newly bundled DVA skill") {
			t.Fatalf("multi-destination legacy expansion ignored later collision: %v", err)
		}
		if _, err := os.Stat(claimDestination(destinations[0], "dva-ci")); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("earlier legacy destination migrated before later collision: %v", err)
		}
	})
}

func TestInvalidReceiptReportedAndRefused(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeOpenCode)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	path := receiptPath(options.StateRoot, destinations[0].path)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("not json"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err == nil {
		t.Fatal("install with invalid receipt succeeded")
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "invalid-receipt" {
		t.Fatalf("status = %s", status.Destinations[0].Status)
	}
}

func TestStatusIdentifiesForeignCollisionAndReceiptPaths(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeProject, RuntimeClaudeCode)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(destinations[0].path, "dva"), 0o755); err != nil {
		t.Fatal(err)
	}
	status, err := Status(options)
	if err != nil {
		t.Fatal(err)
	}
	if status.Destinations[0].Status != "foreign-conflict" {
		t.Fatalf("status = %s", status.Destinations[0].Status)
	}
	for _, value := range []string{"dva/SKILL.md", "dva-config/references/a.md", "dva-ci/references/execution.md", "dva-ci.md"} {
		if !validReceiptPath(value) {
			t.Fatalf("valid receipt path rejected: %q", value)
		}
	}
	for _, value := range []string{"../dva/SKILL.md", "dva/../x", "dva-config/../../x", "/dva/SKILL.md", "other/SKILL.md", "dva-ci/../x", "other.md"} {
		if validReceiptPath(value) {
			t.Fatalf("invalid receipt path accepted: %q", value)
		}
	}
}

func TestSymlinkCollisionAndLegacyConfigAreNeverReplaced(t *testing.T) {
	t.Parallel()
	options := testOptions(t, ScopeUser, RuntimeCodex)
	_, destinations, err := resolve(options)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(destinations[0].path, 0o755); err != nil {
		t.Fatal(err)
	}
	legacy := filepath.Join(destinations[0].path, "config")
	if err := os.MkdirAll(legacy, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(legacy, "SKILL.md"), []byte("legacy"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Install(options); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(legacy, "SKILL.md")); err != nil {
		t.Fatalf("legacy config skill was removed: %v", err)
	}

	symlinkOptions := testOptions(t, ScopeUser, RuntimeGrok)
	_, symlinkDestinations, err := resolve(symlinkOptions)
	if err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(t.TempDir(), "target")
	if err := os.MkdirAll(target, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(symlinkDestinations[0].path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, symlinkDestinations[0].path); err != nil {
		t.Skipf("symlink unavailable: %v", err)
	}
	if _, err := Install(symlinkOptions); err == nil {
		t.Fatal("symlink destination install succeeded")
	}
}

func TestReplaceSkillDirectoriesRollsBackEarlierMove(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	for _, name := range bundled.Names {
		root := filepath.Join(destination, name)
		if err := os.MkdirAll(root, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "old-marker"), []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	renameCalls := 0
	failingRename := func(oldPath, newPath string) error {
		renameCalls++
		if renameCalls == 3 {
			return errors.New("injected second-skill backup failure")
		}
		return os.Rename(oldPath, newPath)
	}
	if _, _, err := replaceSkillDirectoriesWithRename(destination, files, true, ownedSkillNames(files), failingRename); err == nil {
		t.Fatal("replacement succeeded despite injected failure")
	}
	for _, name := range bundled.Names {
		contents, err := os.ReadFile(filepath.Join(destination, name, "old-marker"))
		if err != nil {
			t.Fatalf("%s old directory was not restored: %v", name, err)
		}
		if string(contents) != name {
			t.Fatalf("%s marker = %q", name, contents)
		}
	}
	stages, err := filepath.Glob(filepath.Join(destination, ".dva-skill-stage-*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(stages) != 0 {
		t.Fatalf("staging directories remain: %v", stages)
	}
}

func TestClaimedReplacementRefusesLateAddedSkillCollision(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	for _, name := range []string{"dva", "dva-config"} {
		root := filepath.Join(destination, name)
		if err := os.MkdirAll(root, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "old-marker"), []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	oldFiles := withoutCISkill(files)
	foreign := filepath.Join(destination, "dva-ci", "foreign-marker")
	injected := false
	rename := func(oldPath, newPath string) error {
		if !injected && oldPath == filepath.Join(destination, "dva") {
			injected = true
			if err := os.MkdirAll(filepath.Dir(foreign), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(foreign, []byte("foreign"), 0o644); err != nil {
				return err
			}
		}
		return os.Rename(oldPath, newPath)
	}
	if _, _, err := replaceSkillDirectoriesWithRename(destination, files, true, ownedSkillNames(oldFiles), rename); err == nil || !strings.Contains(err.Error(), "refusing collision") {
		t.Fatalf("replacement accepted late foreign added-skill collision: %v", err)
	}
	contents, err := os.ReadFile(foreign)
	if err != nil || string(contents) != "foreign" {
		t.Fatalf("late foreign collision changed = %q, %v", contents, err)
	}
	for _, name := range []string{"dva", "dva-config"} {
		contents, err := os.ReadFile(filepath.Join(destination, name, "old-marker"))
		if err != nil || string(contents) != name {
			t.Fatalf("%s old directory was not restored = %q, %v", name, contents, err)
		}
	}
}

func TestNewInstallReplacementRefusesLateCollision(t *testing.T) {
	t.Parallel()
	destination := t.TempDir()
	collision := filepath.Join(destination, "dva")
	if err := os.MkdirAll(collision, 0o755); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(collision, "foreign-marker")
	if err := os.WriteFile(marker, []byte("foreign"), 0o644); err != nil {
		t.Fatal(err)
	}
	files, err := bundledFiles()
	if err != nil {
		t.Fatal(err)
	}
	if _, _, err := replaceSkillDirectories(destination, files, false); err == nil {
		t.Fatal("new install replaced a collision created after preflight")
	}
	contents, err := os.ReadFile(marker)
	if err != nil {
		t.Fatalf("foreign collision was removed: %v", err)
	}
	if string(contents) != "foreign" {
		t.Fatalf("foreign marker changed: %q", contents)
	}
}

func testOptions(t *testing.T, scope Scope, runtimes ...Runtime) Options {
	t.Helper()
	root := t.TempDir()
	return Options{
		Scope:       scope,
		Runtimes:    runtimes,
		HomeDir:     filepath.Join(root, "home"),
		ProjectRoot: filepath.Join(root, "project"),
		StateRoot:   filepath.Join(root, "state"),
	}
}

func withoutCISkill(files []fileHash) []fileHash {
	result := make([]fileHash, 0, len(files))
	for _, file := range files {
		if !strings.HasPrefix(file.Path, "dva-ci/") && file.Path != "dva-ci.md" {
			result = append(result, file)
		}
	}
	return result
}

func containsSkillFiles(files []fileHash, skill string) bool {
	for _, file := range files {
		if strings.HasPrefix(file.Path, skill+"/") || file.Path == skill+".md" {
			return true
		}
	}
	return false
}

// reduceClaimedBundleToTwoSkills models a pre-dva-ci current-schema install:
// it retains the two active DVA claims, receipt, and installed directories.
func reduceClaimedBundleToTwoSkills(t *testing.T, options Options) (destination, receipt) {
	t.Helper()
	installed, err := Install(options)
	if err != nil {
		t.Fatal(err)
	}
	target := destination{path: installed.Destinations[0].Destination, runtimes: options.Runtimes}
	return target, reduceClaimedBundleAtTarget(t, options, target)
}

func reduceClaimedBundleAtTarget(t *testing.T, options Options, target destination) receipt {
	t.Helper()
	receiptFile := receiptPath(options.StateRoot, target.path)
	record, found, err := readReceipt(receiptFile)
	if err != nil || !found {
		t.Fatalf("read claimed receipt = (%#v, %t, %v)", record, found, err)
	}
	record.Files = withoutCISkill(record.Files)
	record.BundleSHA = sourceBundleSHA(record.Files)
	ciPath := claimDestination(target, "dva-ci")
	if err := os.RemoveAll(ciPath); err != nil {
		t.Fatal(err)
	}
	ciClaimDestination, err := skillclaim.CanonicalDestination(ciPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(skillclaim.Path(filepath.Dir(options.StateRoot), ciClaimDestination)); err != nil {
		t.Fatal(err)
	}
	if err := writeReceipt(receiptFile, record); err != nil {
		t.Fatal(err)
	}
	return record
}

func assertClaimedBundleState(t *testing.T, options Options, target destination, record receipt) {
	t.Helper()
	current, found, err := readReceipt(receiptPath(options.StateRoot, target.path))
	if err != nil || !found {
		t.Fatalf("read retained receipt = (%#v, %t, %v)", current, found, err)
	}
	if !equalFiles(current.Files, record.Files) || current.BundleSHA != record.BundleSHA || !sameRuntimes(current.Runtimes, record.Runtimes) {
		t.Fatalf("receipt changed after failed expansion = %#v, want %#v", current, record)
	}
	if err := verifyInstalled(target.path, record.Files); err != nil {
		t.Fatalf("old installed bundle changed after failed expansion: %v", err)
	}
	claims, err := projectedClaims(target, options.Scope, record.Runtimes, skillBundle{files: record.Files}, skillclaim.StateActive, "rollback-check")
	if err != nil {
		t.Fatal(err)
	}
	if err := verifyClaimsUnlocked(filepath.Dir(options.StateRoot), claims); err != nil {
		t.Fatalf("old claims changed after failed expansion: %v", err)
	}
	ciClaimDestination, err := skillclaim.CanonicalDestination(claimDestination(target, "dva-ci"))
	if err != nil {
		t.Fatal(err)
	}
	if _, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), ciClaimDestination); err != nil || found {
		t.Fatalf("new dva-ci claim survived failed expansion = (%t, %v)", found, err)
	}
}

func sameRuntimes(left, right []Runtime) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func sameStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func assertClaimConsumers(t *testing.T, options Options, destination string, want []string) {
	t.Helper()
	for _, name := range bundled.Names {
		claim, found, err := skillclaim.Read(filepath.Dir(options.StateRoot), filepath.Join(destination, name))
		if err != nil {
			t.Fatal(err)
		}
		if !found {
			t.Fatalf("claim for %s is missing", name)
		}
		if !sameStrings(claim.Consumers, want) {
			t.Fatalf("claim %s consumers = %v, want %v", name, claim.Consumers, want)
		}
	}
}

func assertRuntimeStatuses(t *testing.T, got []RuntimeStatus, want map[Runtime]string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("runtime statuses = %v, want %v", got, want)
	}
	for _, status := range got {
		if wantStatus, ok := want[status.Runtime]; !ok || wantStatus != status.Status {
			t.Fatalf("runtime status %s = %s, want %s", status.Runtime, status.Status, wantStatus)
		}
		delete(want, status.Runtime)
	}
	if len(want) != 0 {
		t.Fatalf("missing runtime statuses: %v", want)
	}
}
